graphql:
  packages:
    - "gropius"
graphglue:
  includeSkipField: true
management:
  endpoints:
    web:
      base-path: /
logging:
  level:
    org:
      springframework:
        data:
          neo4j:
            cypher:
              unrecognized: ERROR