graphql:
  packages:
    - "gropius"
graphglue:
  includeSkipField: true
logging:
  level:
    org:
      springframework:
        data:
          neo4j:
            cypher:
              unrecognized: ERROR