graphql:
  packages:
    - "gropius"
spring:
  neo4j:
    uri: "bolt://localhost:7687"
  data:
    mongodb:
      host: "localhost"
      port: 27017
      database: "gropius"
      username: "root"
      password: "root"
      "authentication-database": admin
      "auto-index-creation": true
logging:
  level:
    #org.springframework.data.neo4j: ERROR
    org.springframework.data.neo4j: TRACE
    io.github.graphglue: ERROR
    gropius.sync: TRACE
server:
  port: 0