name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

env:
  NODE_OPTIONS: '--max_old_space_size=6144'

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Execute Gradle build
        run: ./gradlew build dokkaHtmlMultiModule
      - name: Save graphql schemas
        run: |
          chmod +x ./website/scripts/generate-graphql-schema.sh
          ./website/scripts/generate-graphql-schema.sh
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm
          cache-dependency-path: "**/package-lock.json"
      - name: Install login-service dependencies
        run: ./gradlew login-service:npm_ci
      - name: Save openapi schemas
        run: |
          chmod +x ./website/scripts/generate-openapi-schema.sh
          ./website/scripts/generate-openapi-schema.sh
      - name: Modify Dokka output
        uses: graphglue/dokka-html-mdx-transform@v1.7.20
        with:
          src: "build/dokka/htmlMultiModule"
          modules: |
            core
            api-common
            api-public
            api-internal
            sync
            github
            jira
          dest: "website/docs"
          folder: "api"
      - name: Install dependencies
        run: npm ci
        working-directory: website
      - name: Update graphql documentation
        run: |
          chmod +x ./website/scripts/update-graphql-doc.sh
          ./website/scripts/update-graphql-doc.sh
      - name: Update rest documentation
        run: |
          chmod +x ./website/scripts/update-rest-doc.sh
          ./website/scripts/update-rest-doc.sh
      - name: Build website
        run: npm run build
        working-directory: website
      # Popular action to deploy to GitHub Pages:
      # Docs: https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-docusaurus
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          # Build output to publish to the `gh-pages` branch:
          publish_dir: ./website/build
          force_orphan: true
          external_repository: ccims/gropius-backend-docs
          publish_branch: main